// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users.proto

package grpc

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1UsersMock struct{}

func (m *V1UsersMock) Create(ctx context.Context, req *CreateUser) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        500,
				FirstName: "ullam",
				LastName:  "ea",
				Email:     "est_beatae@Skaboo.org",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindById(ctx context.Context, req *FindByIdRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        869,
				FirstName: "necessitatibus",
				LastName:  "vel",
				Email:     "labore_occaecati@Yadel.mil",
				Visible:   false,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        95,
				FirstName: "et",
				LastName:  "iste",
				Email:     "tReyes@Divanoodle.edu",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) Update(ctx context.Context, req *UpdateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        148,
				FirstName: "dolores",
				LastName:  "voluptatum",
				Email:     "ClarenceNguyen@Babblestorm.mil",
				Visible:   false,
			},
		}
	return res, nil
}
